version: "3"
services:
  proxy:
    build: ./proxy
    ports:
      - "8080:8080"
    links:
      - "server"

  server:
    build: ./server
    volumes:
      - ./server/:/go/src/grpc-web-react-go/server
    ports:
      - "9090:9090"
    container_name: "server"

  client:
    build: ./client
    volumes:
      - ./client/src:/client/src
      - ./client/public:/client/public
    ports:
      - "3000:3000"